# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Iris < Formula
  desc "A highly customizable, blazing fast and context-aware CLI autocomplete/navigation tool"
  homepage "https://github.com/versenilvis/iris"
  version "0.4.19"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/versenilvis/IRIS/releases/download/v0.4.19/iris_darwin_amd64.tar.gz"
      sha256 "19dfcecc91558056ff169ab06b51e263d093d97a5602e91baddd7eacacca3964"

      define_method(:install) do
        bin.install "iris"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/versenilvis/IRIS/releases/download/v0.4.19/iris_darwin_arm64.tar.gz"
      sha256 "83565c0d14a345255a23b09fff7a3a2da60c5c739d646dcc39df4e0b98c0667c"

      define_method(:install) do
        bin.install "iris"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/versenilvis/IRIS/releases/download/v0.4.19/iris_linux_amd64.tar.gz"
      sha256 "4b289a54258462349c41413c27e3dac9ee297e57570c1dc18375be430003b2e6"
      define_method(:install) do
        bin.install "iris"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/versenilvis/IRIS/releases/download/v0.4.19/iris_linux_arm64.tar.gz"
      sha256 "1a4fbfe5d2e51715a718dc3e47256ce3d7ab9dd28c6eb043db39ade5dce32c43"
      define_method(:install) do
        bin.install "iris"
      end
    end
  end

  def caveats
    <<~EOS
      To completely remove IRIS configurations and shell hooks,
      please run 'iris uninstall' BEFORE removing this package, or manually
      clean up ~/.config/iris and your shell RC files (e.g. ~/.zshrc).
    EOS
  end

  test do
    system "#{bin}/iris", "--help"
  end
end
