# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Iris < Formula
  desc "A highly customizable, blazing fast and context-aware CLI autocomplete/navigation tool"
  homepage "https://github.com/versenilvis/iris"
  version "0.4.21"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/versenilvis/IRIS/releases/download/v0.4.21/iris_darwin_amd64.tar.gz"
      sha256 "f8e961791d8aaf6b9856699cdfcc5f52956f4fb78d6166e1ea7dd90ebdd1edb2"

      define_method(:install) do
        bin.install "iris"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/versenilvis/IRIS/releases/download/v0.4.21/iris_darwin_arm64.tar.gz"
      sha256 "8b3c4696a37d5d06cbee31815f78fa73001ba7465e7beac2485b6b693a548cdc"

      define_method(:install) do
        bin.install "iris"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/versenilvis/IRIS/releases/download/v0.4.21/iris_linux_amd64.tar.gz"
      sha256 "ba29506a43d623171896588191f14b3768bc4d21c33119a021db221b81c0d97b"
      define_method(:install) do
        bin.install "iris"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/versenilvis/IRIS/releases/download/v0.4.21/iris_linux_arm64.tar.gz"
      sha256 "64a174033f9e90ccc66e40dee17e604e85805ab28130540b88ff6f9a4468437a"
      define_method(:install) do
        bin.install "iris"
      end
    end
  end

  def caveats
    <<~EOS
      To completely remove IRIS configurations and shell hooks,
      please run 'iris uninstall' BEFORE removing this package, or manually
      clean up ~/.config/iris and your shell RC files (e.g. ~/.zshrc).
    EOS
  end

  test do
    system "#{bin}/iris", "--help"
  end
end
